---

- serialize: dest=/etc/sensu/conf.d/checks/standalone.json
  args:
    data:
      checks:
        cpu:
          command: /etc/sensu/community/plugins/system/check-cpu.rb -w 80 -c 90
          standalone: true
          handlers:
            - pagerduty
          interval: 30
          notification: cpu check failed
          occurrences: 2
          auto_resolve: true
        disk:
          command: /etc/sensu/community/plugins/system/check-disk.rb
          standalone: true
          handlers:
            - pagerduty
          interval: 30
          notification: disk check failed
          occurrences: 2
          auto_resolve: true
        check-mnt-writable:
          command: /etc/sensu/community/plugins/system/check-fs-writable.rb -d /mnt
          standalone: true
          handlers:
            - pagerduty
          interval: 30
          notification: failed to write on /mnt
          occurrences: 2
          auto_resolve: true
        vmstat-metrics:
          type: metric
          command: /etc/sensu/community/plugins/system/vmstat-metrics.rb --scheme stats.{{ ansible_hostname }}
          standalone: true
          handlers:
            - graphite
          interval: 20
        load-metrics:
          type: metric
          command: /etc/sensu/community/plugins/system/load-metrics.rb --scheme stats.{{ ansible_hostname }}
          standalone: true
          handlers:
            - graphite
          interval: 20
  notify: restart sensu-client
